AWS_REGION_NAME = "us-east-1"

# for prod
ENCRYPTION_KEY_ID = "YOUR_ENCRYPTION_KEY_ID"
ENCRYPTION_ACCESS_KEY_ID = "YOUR_ENCRYPTION_ACCESS_KEY_ID"
ENCRYPTION_SECRET_ACCESS_KEY_ID = "YOUR_ENCRYPTION_SECRET_ACCESS_KEY_ID"
